version: "2"
services:
  app:
    image: node:9-slim
    ports:
      - 4000:80
    environment:
      - DEBUG=
      - FORCE_COLOR=1
      - NODE_ENV=development
      - REGISTRY_HOST=${REGISTRY_HOST}
      - REGISTRY_DOMAIN=${REGISTRY_HOST}
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_SSL=${REGISTRY_SSL}
    volumes:
      - .:/srv/app
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js

