version: "2"
services:
  app:
    image: jc21/node
    ports:
      - ${HTTP_PORT}:80
    environment:
      - DEBUG=${DEBUG}
      - FORCE_COLOR=1
      - NODE_ENV=development
      - REGISTRY_HOST=${REGISTRY_HOST}
      - REGISTRY_DOMAIN=${REGISTRY_HOST}
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_SSL=true
    volumes:
      - .:/srv/app
      - ./.yarnrc:/root/.yarnrc
      - /usr/local/share/.cache/yarn:/usr/local/share/.cache/yarn
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js

