version: "2"
services:
  app:
    image: jc21/node
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry
      - REGISTRY_DOMAIN=registry.example.com
      - REGISTRY_STORAGE_DELETE_ENABLED=
    volumes:
      - .:/srv/app
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js

